"""Add circular foreign keys

Revision ID: cce7a0f9c653
Revises: 4d0d79eadbda
Create Date: 2023-04-10 20:14:47.495528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce7a0f9c653'
down_revision = '4d0d79eadbda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('founder_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(op.f('fk_organizations_founder_id_users'), 'organizations', 'users', ['founder_id'], ['id'])
    op.add_column('users', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_users_organization_id_organizations'), 'users', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_organization_id_organizations'), 'users', type_='foreignkey')
    op.drop_column('users', 'organization_id')
    op.drop_constraint(op.f('fk_organizations_founder_id_users'), 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'founder_id')
    # ### end Alembic commands ###
